training_pipeline_config:
  pipeline_name: credit
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: https://www.kaggle.com/datasets/uciml/default-of-credit-card-clients-dataset/download?datasetVersionNumber=1
  data_ingestion_artifact_dir: data_ingestion
  balanced_dataset_dir: balanced_dataset
  raw_data_dir: raw_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 

data_validation_config:
  data_validation_artifact_dir: data_validation
  schema_dir: config
  schema_file_name: schema.yaml
  report_file_name: report.json
  report_page_file_name: report.html