training_pipeline_config:
  pipeline_name: credit
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: https://www.kaggle.com/datasets/uciml/default-of-credit-card-clients-dataset/download?datasetVersionNumber=1
  raw_data_dir: raw_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 